server:
  port: 6000

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        watch:
          enabled: true
        watch-delay: 1000
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
    gateway:
      discovery:
        locator:
          enabled: true

  config:
    import:
      - optional:nacos:application-@profiles.active@.yaml
      - optional:nacos:${spring.application.name}-@profiles.active@.yaml

