include:
  - path: ./docker-compose-base.yaml
    env_file: ./.env

services:
  nexfly-gateway:
    depends_on:
      nexfly-mysql:
        condition: service_healthy
      nexfly-nacos:
        condition: service_healthy
    image: registry.cn-shenzhen.aliyuncs.com/nexfly/nexfly-gateway:${NEXFLY_VERSION}
    container_name: nexfly-gateway
    ports:
      - 6000:6000
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=${NACOS_ADDR}
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=${NACOS_ADDR}
      - SPRING_CLOUD_NACOS_DISCOVERY_USERNAME=${NACOS_USERNAME}
      - SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD=${NACOS_PASSWORD}
      - TZ=${TIMEZONE}
    networks:
      - nexfly
    restart: always

  nexfly-auth:
    depends_on:
      nexfly-mysql:
        condition: service_healthy
      nexfly-nacos:
        condition: service_healthy
    image: registry.cn-shenzhen.aliyuncs.com/nexfly/nexfly-auth:${NEXFLY_VERSION}
    container_name: nexfly-auth
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=${NACOS_ADDR}
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=${NACOS_ADDR}
      - SPRING_CLOUD_NACOS_DISCOVERY_USERNAME=${NACOS_USERNAME}
      - SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD=${NACOS_PASSWORD}
      - TZ=${TIMEZONE}
    networks:
      - nexfly
    restart: always

  nexfly-system:
    depends_on:
      nexfly-mysql:
        condition: service_healthy
      nexfly-nacos:
        condition: service_healthy
      nexfly-elasticsearch:
        condition: service_healthy
    image: registry.cn-shenzhen.aliyuncs.com/nexfly/nexfly-system:${NEXFLY_VERSION}
    container_name: nexfly-system
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=${NACOS_ADDR}
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=${NACOS_ADDR}
      - SPRING_CLOUD_NACOS_DISCOVERY_USERNAME=${NACOS_USERNAME}
      - SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD=${NACOS_PASSWORD}
      - TZ=${TIMEZONE}
    networks:
      - nexfly
    restart: always

  nexfly-web:
    depends_on:
      nexfly-mysql:
        condition: service_healthy
    image: registry.cn-shenzhen.aliyuncs.com/nexfly/nexfly-web:${NEXFLY_VERSION}
    container_name: nexfly-web
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./nginx/nexfly.conf:/etc/nginx/conf.d/nexfly.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=${TIMEZONE}
    networks:
      - nexfly
    restart: always